### ISSUE TITLE
Save member' profile image

### ISSUE THREAD

**Issue by zaghammehmood** [omeryousaf/cbs_community#2]
save member’s profile images in his member record in couchdb

**Comment by omeryousaf** [comment]
Pa Zagham! its done https://github.com/omeryousaf/cbs_community/commit/bcd904db78934f84b3b2d4184daf73cb61dc2696. there are some changes needed in profile image css but functionality is working alright.

**Comment by omeryousaf** [comment]
@zaghammehmood aenu wi close karo unless you have any other suggestions on this.
