### ISSUE TITLE
Separate Url of recently uploaded dp 

### ISSUE THREAD

**Issue by zaghammehmood** [omeryousaf/cbs_community#3]
keep the url of the most recently uploaded dp in a separate field in same record
and
use this link to the image on profile page

**Comment by omeryousaf** [comment]
https://github.com/omeryousaf/cbs_community/commit/bcd904db78934f84b3b2d4184daf73cb61dc2696, done.

**Comment by omeryousaf** [comment]
@zaghammehmood aenu close kar deo..:p apologies for closing it myself earlier. 

btw, there is an interesting update on this one too. checkout this https://github.com/omeryousaf/cbs_community/commit/566597b24351821b77fe22df52efc5b8ed552a23. previously, the address of the db server was exposed at frontend becoz i was serving image directly from couchdb. but in the above mentioned commit, thanks to @abdraf for showing me how to pipe streams, i was able to move the db server ip from frontend to backend.
